### ISSUE TITLE
Error when creating a release with draft: false 

### ISSUE THREAD

**Issue by tovoro** [akkuman/gitea-release-action#4]
Hi everyone

When I try to create a release with draft: false I get the following error: 

```
[1](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-1)
ApiError: Internal Server Error
[2](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-2)
    at catchErrorCodes (file:///run/act/actions/akkuman-gitea-release-action@v1/dist/index.js:9809:15)
[3](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-3)
    at file:///run/act/actions/akkuman-gitea-release-action@v1/dist/index.js:98[4](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-4)0:17
4
    at Generator.next (<anonymous>)
[5](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-5)
    at fulfilled (file:///run/act/actions/akkuman-gitea-release-action@v1/dist/index.js:9593:58)
[6](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-6)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[7](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-7)
  url: 'https://redacted/api/v1/repos/redacted/redacted/releases/1776',
[8](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-8)
  status: 500,
[9](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-9)
  statusText: 'Internal Server Error',
[10](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-10)
  body: { message: '', url: 'https://redacted/api/swagger' },
[11](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-11)
  request: {
[12](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-12)
    method: 'PATCH',
[13](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-13)
    url: '/repos/{owner}/{repo}/releases/{id}',
[14](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-14)
    path: { owner: 'redacted', repo: 'redacted', id: 1776 },
[15](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-15)
    body: {
[16](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-16)
      body: '',
[17](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-17)
      draft: false,
[18](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-18)
      name: 'e3m-dev-beta',
[19](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-19)
      prerelease: false,
[20](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-20)
      tag_name: '1.0.0',
[21](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-21)
      target_commitish: ''
[22](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-22)
    },
[23](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-23)
    errors: { '404': 'APINotFound is a not found empty response' }
[24](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-24)
  }
[25](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-25)
}
[26](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-26)
::error::Internal Server Error
``` 

Same action workfs fine with draft: true

Is this a bug or am I doing something wrong? On the GUI I can create a release without issue.

**Comment by akkuman** [comment]
@tovoro Can you provide a repository or yaml sample？

**Comment by tovoro** [comment]
```
name: e3MobileN Release

on:
  issue_comment:
    types: [created]
  push:
    branches:
      - 'xxx*'

jobs:
  release:
    name: xx Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:


###default build
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          ref: 'e3m-release-beta'

      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

   
      - name: Install dependencies
        run: npm ci

      - name: Build Default
        run: ng build

      - name: Parse ./src/assets/config/config_json to get version
        run: echo "CONFIG_JSON=$(jq -c . < ./src/assets/config/config.json)" >> $GITHUB_ENV


      - name: Create default Release Archive
        uses: thedoctor0/zip-release@master
        with:
          directory: /tmp
          filename: 'e3MobileN-default-${{ fromJson(env.CONFIG_JSON).version }}.zip'
          path: '${{ GITEA.WORKSPACE }}/dist/e3mobile'


      - name: Create Release
        uses: akkuman/gitea-release-action@v1
        with:
          draft: true
          prerelease: false
          release_name: 'xxx-${{ fromJson(env.CONFIG_JSON).version }}'
          tag_name: '${{ fromJson(env.CONFIG_JSON).version }}'
          target_commitish: 6cfb7dc4cf424f4d7d0b3380b36d060495de4b93 #git rev-parse origin/xxx-release-beta
          files: |-
            /tmp/xxx-*.zip

**Comment by akkuman** [comment]
@tovoro I can't seem to find the problem. Can you provide a complete log?

**Comment by akkuman** [comment]
```
[10](https://redacted/redacted/redacted/actions/runs/65#jobstep-9-10)
  body: { message: '', url: 'https://redacted/api/swagger' },
```

According to this log, it is possible that the gitea host is not configured correctly, please check if your gitea/act_runner is configured correctly
